### PR TITLE
Feature/allow eslint 5.x / stylelint 9.x as peer dependencies

### PR DESCRIPTION
**Pull request by jesse-mm**
Currently after installing these deps within our project it throws a lot of warnings for these specific packages.

We are running ESLint 5.6.x along with the newest Stylint 9.6.x using these configurations, without any problems.

### CODE REVIEW

**Comment by moelders** [comment]
We are planning to update `eslint` to the version 5, however, it could work for the time being.

We are going to check it and release a new version.

**Comment by moelders** [comment]
I have changed the destination branch to prepare the release.

Thanks @jesse-mm!

**Review by moelders — APPROVED** [review]
LGTM

**Comment by jesse-mm** [comment]
Thanks :)

**Comment by moelders** [comment]
@jesse-mm, all the packages have been updated. The new version is only compatible with ESLint 5 in order to be able to add new rules to the configurations.

**Comment by jesse-mm** [comment]
Thank you. That will work for us :). I'll update our project dependencies and see if we can get it compatible with the rule changes 👍 .

**Pull request merged**
